controller:
  admin:
    username: admin
    password: admin123

  serviceType: NodePort
  nodePort: 30080

  # Plugins to enable pipelines, git, github integration
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - github
    - pipeline-stage-view

  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

  JCasC:
    configScripts: {}

persistence:
  enabled: false   # KIND is ephemeral

