controller:
  admin:
    username: admin
    password: admin123

  serviceType: NodePort
  nodePort: 30080

  installPlugins:
    - kubernetesi:1.39.3
    - workflow-aggregator:2.468
    - git:4.15.1
    - github:1.34.0
    - helm:1.1.0
    - pipeline-stage-view:2.28

  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

persistence:
  enabled: true
  size: 8Gi

